title: gdk #Your awesome title
author: Fleuron Gnadekpa
email: vilfleur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the blog of Fleuron Gnadekpa. I’m glad you are here.
  I am an inspiring Frontend Developer who writes to share his progress.

# social links
twitter_username: FGnadekpa
github_username:  fleuronvilik

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
